import { ContentItem } from './types';

export const initialData: ContentItem[] = [
    { id: 1, title: 'Космические отголоски', description: 'Одинокий астронавт обнаруживает таинственный сигнал с края галактики, заставляющий ее усомниться в самой реальности.', image: 'https://placehold.co/400x600', type: 'movie', votes: { up: 1204, down: 58 }, aiHint: 'astronaut space', actors: ['Анна Ковалева', 'Максим Волков'], director: 'Елена Петрова', country: 'Россия', genre: 'Фантастика' },
    { id: 2, title: 'Хроники кибер-города', description: 'В залитом неоном мегаполисе детектив охотится на вышедший из-под контроля ИИ, который научился манипулировать человеческими воспоминаниями.', image: 'https://placehold.co/400x600', type: 'series', votes: { up: 2589, down: 112 }, aiHint: 'cyberpunk city', actors: ['Дмитрий Соколов', 'Ольга Белова'], director: 'Алексей Сидоров', country: 'США', genre: 'Киберпанк' },
    { id: 3, title: 'Последнее королевство', description: 'Историческая драма о рождении Англии, увиденная глазами саксонского дворянина, воспитанного викингами.', image: 'https://placehold.co/400x600', type: 'series', votes: { up: 3450, down: 230 }, aiHint: 'viking warrior', actors: ['Александр Романов', 'Екатерина Морозова'], director: 'Игорь Кузнецов', country: 'Великобритания', genre: 'История' },
    { id: 4, title: 'Глубины океана', description: 'Глубоководная исследовательская группа обнаруживает древнюю цивилизацию, но в бездне они не одни.', image: 'https://placehold.co/400x600', type: 'movie', votes: { up: 987, down: 45 }, aiHint: 'underwater exploration', actors: ['Мария Лебедева', 'Иван Попов'], director: 'Сергей Новиков', country: 'Франция', genre: 'Триллер' },
    { id: 5, title: 'Проект "Химера"', description: 'Секретный правительственный эксперимент по созданию суперсолдат проваливается, высвобождая новую угрозу для мира.', image: 'https://placehold.co/400x600', type: 'series', votes: { up: 1876, down: 301 }, aiHint: 'science fiction', actors: ['Павел Виноградов', 'Елена Козлова'], director: 'Олег Зайцев', country: 'Германия', genre: 'Боевик' },
    { id: 6, title: 'Нулевая гравитация', description: 'Конкурирующие корпорации сражаются за контроль над редким ресурсом, найденным только на астероидах, что приводит к войне в космосе.', image: 'https://placehold.co/400x600', type: 'movie', votes: { up: 1543, down: 99 }, aiHint: 'spaceship battle', actors: ['Артем Богданов', 'Виктория Федорова'], director: 'Антон Павлов', country: 'Канада', genre: 'Космоопера' },
    { id: 7, title: 'Золотая клетка', description: 'В викторианском Лондоне молодая женщина с тайным прошлым проникает в высшее общество, чтобы разоблачить темный заговор.', image: 'https://placehold.co/400x600', type: 'series', votes: { up: 2100, down: 150 }, aiHint: 'victorian london', actors: ['София Никитина', 'Михаил Егоров'], director: 'Людмила Голубева', country: 'Великобритания', genre: 'Детектив' },
    { id: 8, title: 'Земля кочевников', description: 'После глобальной катастрофы одинокий странник путешествует по опустошенному ландшафту в поисках мифического убежища.', image: 'https://placehold.co/400x600', type: 'movie', votes: { up: 1120, down: 88 }, aiHint: 'post apocalyptic', actors: ['Ирина Семенова', 'Владимир Орлов'], director: 'Юрий Беляев', country: 'Австралия', genre: 'Постапокалипсис' },
];
